### ISSUE TITLE
Easy way to ingest market data from a Provider?

### ISSUE THREAD

**Issue by arthurcolle** [fremantle-industries/tai#228]
Sorry for opening an issue for this, but I'm finding it hard to use this library without many examples. 

How would I just ingest data from say, Deribit, using this library?

**Comment by rupurt** [comment]
Hey @arthurcolle,

Documentation is a little light... ;) Are you looking to ingest order book data or trade data?

**Comment by arthurcolle** [comment]
Orderbook data for now would be a userful example! And no worries about the docs, I understand how it's a challenge to get in-depth docs out the door in the early stages.

**Comment by rupurt** [comment]
`tai` currently only streams order book data. I'd love to have OHLC candles but it's not a focus atm.

I'd suggest looking at the log spread advisor and it's E2E test:

- https://github.com/fremantle-industries/tai/blob/main/apps/examples/test/examples/log_spread/advisor_test.exs
- https://github.com/fremantle-industries/tai/blob/main/apps/examples/lib/examples/log_spread/advisor.ex

**Comment by arthurcolle** [comment]
Appreciate it - I'll try to add OHLC bars in my own work and potentially submit a pull request. 

Thanks for the response, Alex

**Comment by rupurt** [comment]
Sweet. Look forward to it
