### ISSUE TITLE
Seperation of Database from main tai package.

### ISSUE THREAD

**Issue by jnatherley** [fremantle-industries/tai#268]
**Is your feature request related to a problem? Please describe.**
I think there might be a case where a user of Tai would want to use for other tooling, such as analytics of order books or volatility. Therefore the OrderRepo might not be necessary and it might be an additional piece that can be plugged in. What do you think?

Really love the work done here. If i find some time i'll be willing to contribute.

**Comment by rupurt** [comment]
Hey @jnatherley,

I would consider it if there is a good argument. Typically my experience has been that if you're doing data analysis you'll need some sort of database. There are 2 options currently if you want to do data analysis:

- If you don't want to install and run a database you can just configure SQLite and not interact with the orders API
- You can use my [history](https://github.com/fremantle-industries/history) tool, which uses tai under the hood :)

**Comment by jnatherley** [comment]
> Hey @jnatherley,
> 
> I would consider it if there is a good argument. Typically my experience has been that if you're doing data analysis you'll need some sort of database. There are 2 options currently if you want to do data analysis:
> 
> * If you don't want to install and run a database you can just configure SQLite and not interact with the orders API
> * You can use my [history](https://github.com/fremantle-industries/history) tool, which uses tai under the hood :)

I think that's a really good idea.

Yeah i would want to do some analysis but i was considering using something other than Postgres.

**Comment by rupurt** [comment]
If it has an adapter supported by Ecto you can just configure that also. I haven't tested it on anything but SQLite & MySQL

**Comment by jnatherley** [comment]
Closing! Thank you
